- set_fact:
    skip_array: False

- name: Fail if the specified devices do not exist on the host
  stat:
    path: "{{ item }}"
  register: rc
  failed_when: rc.stat.exists == False
  with_items: "{{ array.disks }}"

- name: Check array state
  include: check_array_state.yml
  with_items:
    - "{{ array.disks + [ array.device] }}"
  loop_control:
    loop_var: disk

- when: not skip_array
  block:
  - name: Create arrays
    shell:  "yes | mdadm --create {{ array.device }} --level={{ array.level }}  {% if array.layout is defined %} --layout={{ array.layout }} {% endif %} --raid-devices={{ array.disks | count }} {{ array.disks | join(' ') }}"

  - name: Register mdadm scan output to save md state across reboots
    command: "mdadm --detail --scan"
    register: mdadm_detail_scan

  - name: Save state
    lineinfile:
      dest: "{{ mdadm_conf_path }}"
      regexp: "^{{ mdadm_detail_scan.stdout_lines }}"
      line: "{{ mdadm_detail_scan.stdout }}"
      state: "{{ array.state | default('present') }}"
      create: yes


- when: array.mountpoint is defined
  block:
  - name: Create filesystem
    filesystem:
      fstype: "{{ array.filesystem | default(raid_default_filesystem }}"
      opts: "{{ array.filesystem_opts | default(omit) }}"
      dev: "{{ array.device }}"

  - name: Ensure mountpoint exists
    file:
      path: "{{ array.mountpoint }}"
      state: directory
      owner: "{{ array.owner | default('root') }}"
      group: "{{ array.group | default('root') }}"
      mode:  "{{ array.mode  | default('0755') }}"

  - name: Mount device
    mount:
      name: "{{ array.mountpoint }}"
      src: "{{ array.device }}"
      state: mounted
      opts: "{{ array.mount_opts | default(omit) }}"
      fstype: "{{ array.filesystem | default(raid_default_filesystem) }}"
